# Counting percentage of specific characters in a dna sequence
dna = 'GTACGACGGAGTGTTATAAGATGGGAAATCGGATACCAGATGAAATTGTGGATCAGGTGCAAAAGTCGGCAGATATCGTTGAAGTCATAGGTGATTATGTTCAATTAAAGAAGCAAGGCCGAAACTACTTTGGACTCTGTCCTTTTCATGGAGAAAGCACACCTTCGTTTTCCGTATCGCCCGACAAACAGATTTTTCATTGCTTTGGCTGCGGAGCGGGCGGCAATGTTTTCTCTTTTTTAAGGCAGATGGAAGGCTATTCTTTTGCCGAGTCGGTTTCTCACCTTGCTGACAAATACCAAATTGATTTTCCAGATGATATAACAGTCCATTCCGGAGCCCGGCCAGAGTCTTCTGGAGAACAAAAAATGGCTGAGGCACATGAGCTCCTGAAGAAATTTTACCATCATTTGTTAATAAATACAAAAGAAGGTCAAGAGGCACTGGATTATCTGCTTTCTAGGGGCTTTACGAAAGAGCTGATTAATGAATTTCAGATTGGCTATGCTCTTGATTCTTGGGACTTTATCACGAAATTCCTTGTAAAGAGGGGATTTAGTGAGGCGCAAATGGAAAAAGCGGGTCTCCTGATCAGACGCGAAGACGGAAGCGGATATTTCGACCGCTTCAGAAACCGTGTCATGTTTCCGATCCATGATCATCACGGGGCTGTTGTTGCTTTCTCAGGCAGGGCTCTTGG'
dnalist = list(dna) # convert dna string to list
dnalength = len(dnalist) # getting length of dna list
countA=0 
countG=0
countC=0
countT=0

for element in dnalist: # using for loop to iterate the list and count the occurrences
	if (element == "A"):
		countA+=1	
	elif (element == "C"):
		countC+=1
	elif (element == "G"):
		countG+=1
	elif (element == "T"):
		countT+=1

print ("A: ", round((countA/dnalength)*100), "%") # convert individual count to percentage for each string in the sequence
print ("T: ", round((countT/dnalength)*100), "%")
print ("C: ",round((countC/dnalength)*100), "%")
print ("G: ", round((countG/dnalength)*100), "%")